### ISSUE TITLE
怎么升级支持python protobuf package 4.22.1

### ISSUE THREAD

**Issue by xiantuan** [XiaoMiku01/douyin_danmu#3]

**Comment by xiantuan** [comment]
我用了老师go语言里的dy.proto
改了
// [START csharp_declaration]
option csharp_namespace = "./protobuf";
// [END csharp_declaration]
重新生成.发现不行，老师没时间我就自己再摸索摸索

**Comment by XiaoMiku01** [comment]
Python 的可以看这个项目 https://github.com/YunzhiYike/douyin-live

**Comment by xiantuan** [comment]
蟹蟹！
